### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mzlogin** [mzlogin/awesome-adb#3]
- [x] USB 连接相关
- [x] 无线连接
- [x] 调起 Activity
- [x] 调起 Service
- [x] 发送广播
- [x] 查看/过滤日志
- [x] 显示屏参数输出解析
- [x] 重新挂载 system 分区为可写
- [x] 刷机相关的命令
- [x] adb reboot
- [x] adb root
- [x] 更改 adb 运行端口
- [x] 修改系统时间
- [x] 查看 WiFi 密码
- [x] 查看 Mac 地址
- [x] 点亮/熄灭/解锁屏幕（adb shell input 的各种用法）
- [x] 查看 adb 版本

**Comment by mzlogin** [comment]
Done.

**Comment by codeskyblue** [comment]
还有 

* adb ppp
* adb sideload
* adb get-devpath
* adb keygen
* adb backup
* adb bugreport
* adb forward
* adb reverse
* adb sync

**Comment by longdanie** [comment]
命令太强大不忍直视

**Comment by mzlogin** [comment]
sideload 在文档的刷机相关一节中有所涉及，backup 已在 todo 中。

有些命令我自己没有涉及过，会需要一些时间去了解然后再加入文档，感谢补充，也希望持续关注和提建议，如果有空，也欢迎加入进来撰写一些章节。

再次感谢！ @codeskyblue

**Comment by mzlogin** [comment]
确实是很强大的，毕竟是 Debug Bridge， :smile:

**Comment by codeskyblue** [comment]
大部分都被你写了，我还有一些奇葩方案，有空我再写上去

**Comment by mzlogin** [comment]
欢迎欢迎！先谢过~ @codeskyblue

**Comment by brucezz** [comment]
还有 `adb shell uiautomator dump` 可以得到屏幕中控件信息~

**Comment by mzlogin** [comment]
@brucezz 收到~感谢补充。

**Comment by flyfei** [comment]
- `adb -s <serialNumber> <command>` 给指定设备发送指令 e.g.  `adb -s emulator-5556 install test.apk`  `adb -s 192.168.1.10:5555 install test.apk`

**Comment by mzlogin** [comment]
@flyfei 感谢补充，这一点在文档中有体现哈~

<https://github.com/mzlogin/awesome-adb#为命令指定目标设备>

如果你觉得文档中表述方式还可以改进，欢迎探讨和建议！ :)

**Comment by xudafeng** [comment]
补充一个Node.js 的封装实现 https://github.com/macacajs/macaca-adb

**Comment by flyfei** [comment]
@mzlogin  我觉得 根据 IP，Port 找到指定设备很实用，有必要提一下。很多设备做测试的是时候会用到

**Comment by mzlogin** [comment]
@flyfei 噢噢……我没有体会到你的重点，你说的有道理，`<IP>:<Port>` 这种形式也是一个 serialNumber，但也并不是所有人都知道这点。我在文档相关章节里追加了说明和举例，@229643542521a4554ab99cab14154d2a89278a73 感谢！

**Comment by mzlogin** [comment]
@xudafeng 我没有找到怎么使用……有说明文档吗？
